# Generated by Django 4.2 on 2025-12-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
